# Generated by Django 3.2.3 on 2021-12-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
