# Generated by Django 3.2.3 on 2022-01-24 16:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation_variation_value'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
                ('variation', django.db.models.manager.Manager()),
            ],
        ),
    ]
