# Generated by Django 3.2.7 on 2021-09-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
