# Generated by Django 3.2.3 on 2022-02-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_variation_managers'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variations',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
